build:
  environment:
    node: 20
    variables:
      NODE_ENV: test
      PORT: 8080
      DB_CONNECTION_STRING: mongodb://localhost:27017/data
      AUTH_TOKEN_SECRET_PATH: './public.pem'

  nodes:
    lint:
      tests:
        override:
          - command: npm ci
          - command: npm run lint

    unit-tests:
      tests:
        override:
          - command: npm ci
          - command: npm run test:unit

    scenario-tests:
      environment:
        variables:
          DB_CONNECTION_STRING: mongodb://localhost:27017/data_test
          AUTH_TOKEN_SECRET_PATH: './test_public.pem'
        services:
          mongodb:
            version: 7
      tests:
        override:
          - command: echo "$TEST_PUBLIC_PEM" > test_public.pem
          - command: npm ci
          - command: npm run test:scen

tools:
  external_code_coverage:
    enabled: false

  javascript:
    enabled: true
    code_rating: true
    tests:
      enabled: true

  eslint:
    config:
      use_project_config: true
