services:
  mongodb-data:
    image: mongo:7.0.4
    restart: always
    ports:
      - 127.0.0.1:27018:27017
    volumes:
      - volume-mongo-data:/data/db
    networks:
      - network-data

  data-server:
    build:
      context: .
    restart: always
    depends_on:
      - mongodb-data
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_CONNECTION_STRING: mongodb://mongodb-data:27017/data
      AUTH_TOKEN_SECRET_PATH: /public.pem
      BASE_URL: '/data'
    ports:
      - 5054:3000
    volumes:
      - /home/ubuntu/app/data-server/public.pem:/public.pem:ro
    networks:
      - network-data

volumes:
  volume-mongo-data:

networks:
  network-data:
