name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  NODE_ENV: test
  PORT: 8080
  DB_CONNECTION_STRING: mongodb://localhost:27017/data
  AUTH_TOKEN_SECRET_PATH: './public.pem'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run lint

  test-unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run test:unit

  test-scen:
    name: Scenario Tests
    runs-on: ubuntu-latest
    env:
      DB_CONNECTION_STRING: mongodb://localhost:27017/data_test
      AUTH_TOKEN_SECRET_PATH: ./test_public.pem
    steps:
      - uses: actions/checkout@v4

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: 7

      - name: Write public key
        run: echo "${{ secrets.TEST_PUBLIC_PEM }}" > test_public.pem

      - run: npm ci
      - run: npm run test:scen

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [lint, test-unit, test-scen]
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add - > /dev/null
          chmod 700 ~/.ssh
          ssh-keyscan -H ${{ secrets.PRODUCTION_HOST }} >> ~/.ssh/known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        shell: bash

      - name: Start ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy with Docker Compose
        run: |
          ssh root@${{ secrets.PRODUCTION_HOST }} '
            cd /root/app/data-server &&
            docker compose -f docker-compose.yml pull &&
            docker compose -f docker-compose.yml up -d --build
          '

